# This is a generated file. Not intended for manual editing.
services:
  raceapi:
    build:
      context: "C:\\Users\\RhodriSmith\\writemedia\\TestingProjects\\Race\\Race-Portfolio-Api"
      dockerfile: "RaceApi/Dockerfile.debug"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/RaceApi.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "raceapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\adm.rhodri\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\RhodriSmith\\writemedia\\TestingProjects\\Race\\Race-Portfolio-Api\\\
      RaceApi:/app:rw"
    - "C:\\Users\\RhodriSmith\\writemedia\\TestingProjects\\Race\\Race-Portfolio-Api:/src:rw"
    working_dir: "/app"
